NethServer/nethserver-backup-data

root/etc/e-smith/events/actions/backup-data-duplicity

backup-data-duplicity: replace include-globbing-filelist option

---

root/etc/e-smith/events/actions/backup-data-duplicity

backup-data-duplicity: remove stale lockfile. Bug NethServer/dev#5179

---

root/usr/share/nethesis/NethServer/Module/BackupData.php

Fixes https://github.com/NethServer/dev/issues/5235#issuecomment-284698188

Fix vfstypes validation clash

---

root/usr/share/nethesis/NethServer/Module/BackupData.php

Set first day of week from Sunday to Monday

Change first day of week

---

README.rst
createlinks
root/etc/e-smith/db/configuration/defaults/backup-data/IncludeLogs
root/etc/e-smith/templates/etc/backup-data.d/nethserver-backup-data.include/10base
root/usr/share/nethesis/NethServer/Language/en/NethServer_Module_BackupData.php
root/usr/share/nethesis/NethServer/Module/BackupData.php
root/usr/share/nethesis/NethServer/Template/BackupData.php

Include logs

---

root/etc/e-smith/events/actions/backup-data-list-duplicity

list duplicity: fix path for single backup

---

root/usr/share/nethesis/NethServer/Module/BackupData.php

UI: make sure NotifyFrom field is saved

---

root/usr/share/nethesis/NethServer/Module/Dashboard/SystemStatus/Backup.php

Show backup time in human format and not like crontab (only english).

Dashboard: improve data visualization

---

nethserver-backup-data.spec

spec: add missing events dirs

---

root/usr/share/nethesis/NethServer/Language/en/NethServer_Module_BackupData.php
root/usr/share/nethesis/NethServer/Module/BackupData.php

UI: support 1 day retention

---

nethserver-backup-data.spec

This fork contains a fix for retention on daily backups.
NethServer/dev#5776

rsync: switch to kapitainsky fork

---

root/sbin/e-smith/backup-data-wrapper

https://github.com/NethServer/dev/issues/5796

Added epoch timestamp in hooks

---

root/etc/e-smith/events/actions/backup-data-list-rsync

https://github.com/NethServer/dev/issues/5799

backup-data-list. fixed rsync list of latest backup

---

root/etc/e-smith/events/actions/backup-data-rsync
root/etc/e-smith/events/actions/restore-data-rsync

https://github.com/NethServer/dev/issues/5804

Fix non default port for rsync backup

---

root/etc/e-smith/events/actions/backup-data-list-duplicity

https://github.com/NethServer/dev/issues/5898

duplicity list. fixed missing file name with spaces

---

root/etc/e-smith/events/actions/restore-data-rsync

https://github.com/NethServer/dev/issues/5908
Bug introduced in https://github.com/NethServer/nethserver-backup-data/pull/46/files

Fix support for rsync over ssh

---

root/etc/e-smith/events/actions/backup-data-list-duplicity

https://github.com/NethServer/dev/issues/5913

duplicity: use standard output instead of logfile to get filenames

---

NethServer/Restic.pm
root/etc/e-smith/events/actions/restore-data-duplicity
root/etc/e-smith/events/actions/restore-data-restic

Fixes for:
- duplicity
- restic
Rsync isn't affected by this bug.
NethServer/dev#5913

Restore: support files with ' char

---

root/etc/e-smith/events/actions/restore-data-restic

Use 'dump' command for disaster recovery to force
the restore with non-numeric uids and gids
NethServer/dev#6408

restic: preserve owner on disaster recovery

---

root/etc/e-smith/events/actions/restore-data-restic

restic dump: --quiet to avoid garbage in tar format
